# $ jekyll serve --watch --baseurl=
# $ sass --watch assets/_scss:assets/css
  
name: 'Spry Elephant'
tagline: 'Development'
email: ''
phone: ''
twitter: 'digidigo'
github: 'digidigo'
linkedin: 'daveclem'

markdown: rdiscount
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
pygments: true

# url: http://jeffreylarrimore.com
seurl: /sprywebsite/
assets: assets/
relative_permalinks: false
permalink: pretty